### ISSUE TITLE
Installation Module Excavating data, Penetration rates, Hammer data, Installation tidal time series, Installation wind time series do not read correctly from database

### ISSUE THREAD

**Issue by H0R5E** [DTOcean/dtocean#17]
When loading reference data for the installation module the following three variables do not read correctly:

```
2017-03-07 13:51:08,963 - ERROR - root - Reading variables component.excavating generated error: <type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1234, in _read_variables
    fetch_var_ids)
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1135, in _get_read_values
    interface = core.connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_gui\core.py", line 267, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_core\core.py", line 1239, in connect_interface
    interface.safe_connect()
  File "C:\DTOcean\lib\site-packages\aneris\boundary\interface.py", line 748, in safe_connect
    self.connect()
  File "C:\DTOcean\lib\site-packages\aneris\control\factory.py", line 93, in connect
    result = f(cls)
  File "C:\DTOcean\lib\site-packages\dtocean_core\data\definitions.py", line 404, in auto_db
    columns=self.meta.result.tables[1:])
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 364, in read_sql_table
    parse_dates=parse_dates, columns=columns, chunksize=chunksize)
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 1130, in read_table
    chunksize=chunksize)
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 796, in read
    cols = [self.table.c[n] for n in columns]
  File "C:\DTOcean\lib\site-packages\sqlalchemy\util\_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'excavator_day_rate '
```

```
2017-03-07 13:51:09,170 - ERROR - root - Reading variables component.equipment_penetration_rates generated error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1234, in _read_variables
    fetch_var_ids)
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1135, in _get_read_values
    interface = core.connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_gui\core.py", line 267, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_core\core.py", line 1239, in connect_interface
    interface.safe_connect()
  File "C:\DTOcean\lib\site-packages\aneris\boundary\interface.py", line 748, in safe_connect
    self.connect()
  File "C:\DTOcean\lib\site-packages\aneris\control\factory.py", line 93, in connect
    result = f(cls)
  File "C:\DTOcean\lib\site-packages\dtocean_core\data\definitions.py", line 483, in auto_db
    df = pd.read_sql_table(self.meta.result.tables[0],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

```
2017-03-07 13:51:09,404 - ERROR - root - Reading variables component.hammer generated error: <type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1234, in _read_variables
    fetch_var_ids)
  File "C:\DTOcean\lib\site-packages\dtocean_core\pipeline.py", line 1135, in _get_read_values
    interface = core.connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_gui\core.py", line 267, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "C:\DTOcean\lib\site-packages\dtocean_core\core.py", line 1239, in connect_interface
    interface.safe_connect()
  File "C:\DTOcean\lib\site-packages\aneris\boundary\interface.py", line 748, in safe_connect
    self.connect()
  File "C:\DTOcean\lib\site-packages\aneris\control\factory.py", line 93, in connect
    result = f(cls)
  File "C:\DTOcean\lib\site-packages\dtocean_core\data\definitions.py", line 404, in auto_db
    columns=self.meta.result.tables[1:])
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 364, in read_sql_table
    parse_dates=parse_dates, columns=columns, chunksize=chunksize)
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 1130, in read_table
    chunksize=chunksize)
  File "C:\DTOcean\lib\site-packages\pandas\io\sql.py", line 796, in read
    cols = [self.table.c[n] for n in columns]
  File "C:\DTOcean\lib\site-packages\sqlalchemy\util\_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'length double'
```

```
2017-03-16 16:59:58,125 - ERROR - root - Reading variables farm.tidal_series_installation generated error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\pipeline.py", line 1234, in _read_variables
    fetch_var_ids)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\pipeline.py", line 1135, in _get_read_values
    interface = core.connect_interface(project, interface)
  File "c:\users\mtopper\programming\python\git\dtocean-app\dtocean_app\core.py", line 267, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\core.py", line 1239, in connect_interface
    interface.safe_connect()
  File "C:\Anaconda\envs\_dtocean_dev\lib\site-packages\aneris\boundary\interface.py", line 748, in safe_connect
    self.connect()
  File "C:\Anaconda\envs\_dtocean_dev\lib\site-packages\aneris\control\factory.py", line 93, in connect
    result = f(cls)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\data\definitions.py", line 233, in auto_db
    dt_labels.extend(self.meta.result.labels)
TypeError: 'NoneType' object is not iterable
```

```
2017-03-16 16:59:49,348 - ERROR - root - Reading variables farm.wind_series_installation generated error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\pipeline.py", line 1234, in _read_variables
    fetch_var_ids)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\pipeline.py", line 1135, in _get_read_values
    interface = core.connect_interface(project, interface)
  File "c:\users\mtopper\programming\python\git\dtocean-app\dtocean_app\core.py", line 267, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\core.py", line 1239, in connect_interface
    interface.safe_connect()
  File "C:\Anaconda\envs\_dtocean_dev\lib\site-packages\aneris\boundary\interface.py", line 748, in safe_connect
    self.connect()
  File "C:\Anaconda\envs\_dtocean_dev\lib\site-packages\aneris\control\factory.py", line 93, in connect
    result = f(cls)
  File "c:\users\mtopper\programming\python\git\dtocean-core\dtocean_core\data\definitions.py", line 233, in auto_db
    dt_labels.extend(self.meta.result.labels)
TypeError: 'NoneType' object is not iterable
```

**Comment by H0R5E** [comment]
Fixed for 1.1 release.
